name: deploy d2hub to qa

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build with VitePress
        run: npm run docs:build
      # No upload artifact needed, we deploy to a different repo

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dist folder
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy to d2hub-qa.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: dorinandreidragan/d2hub-qa.github.io
          publish_branch: main
          publish_dir: docs/.vitepress/dist
          personal_token: ${{ secrets.D2HUB_QA_GITHUB_TOKEN }}
